version: "{build}"
clone_folder: "c:\\work"

environment:
  global:
    CABOPTS:  "--store-dir=C:\\SR --http-transport=plain-http"
  matrix:
    - GHCVER: "7.8.4.1"
    - GHCVER: "7.10.3.2"
    - GHCVER: "8.0.2"
    - GHCVER: "8.2.2"
    - GHCVER: "8.4.4"
    - GHCVER: "8.6.3"

platform:
  - x64

cache:
 - "C:\\SR"

install:
 - "choco install -y cabal"
 - "choco install -y ghc --version %GHCVER%"
 - "refreshenv"
 - "set PATH=C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin;C:\\ghc\\ghc-%GHCVER%\\bin;%PATH%"
 - "cabal --version"
 - "ghc --version"
 - "cabal %CABOPTS% v2-update -vverbose+nowrap"

build: off
deploy: off

test_script:
 - "cabal %CABOPTS% v2-build -j1 -vnormal+nowrap all"
